version: "3.8"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coursejdbc
      - MYSQL_PASSWORD=root

volumes:
  mysql_db_data:
